version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: crm-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=t4jn3h4slo"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_data:/var/lib/mysql

  crm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - crm-network
    depends_on:
        db:
          condition: service_healthy

networks:
  crm-network:
    driver: bridge

volumes:
  db_data:
