'use strict'
const bcrypt = require('bcrypt')

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        const hashPassword = async (password) => {
            const saltRounds = 10
            const salt = await bcrypt.genSalt(saltRounds)
            return await bcrypt.hash(password, salt)
        }

        try {
            await queryInterface.removeConstraint('Users', 'email')
        } catch (error) {
            console.log('No existing constraint found. Skipping removal.')
        }
        await queryInterface.addConstraint('Users', {
            fields: ['email'],
            type: 'unique',
            name: 'unique_email_constraint',
        })

        const users = [
            {
                id: '0a1868a7-cc98-4b57-8807-2c7f8e556c1b',
                firstName: 'Jakub',
                lastName: 'Prus',
                email: 'jakub@jakub',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '23512d44-e0e0-4ed3-a09c-32603587dbf8',
                firstName: 'Dominik',
                lastName: 'Paczkowski',
                email: 'dominik@dominik',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '9b1e9a92-404c-44e5-bea3-1724d00f1db6',
                firstName: 'Damian',
                lastName: 'Kowalski',
                phoneNumber: '123456789',
                email: 'damian@damian',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'c4889946-9181-4d3b-b3a2-8a980b008546',
                firstName: 'Adrian',
                lastName: 'Nowicki',
                email: 'adrian@adrian',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '98c789ea-049b-4aa3-9b23-5102d0e81c14',
                firstName: 'Skaut',
                lastName: '1',
                email: 'skaut1@skaut',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: '78347847-91f6-452a-b4f0-52d6d8f31ee8',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '493ddad9-0953-4b5c-b7f6-d9ffb7187ea3',
                firstName: 'Skaut',
                lastName: '2',
                email: 'skaut2@skaut',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: 'fdb1d820-b23b-49e6-a5e0-547f9df90686',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'ec63aca1-09d5-42c1-b88e-c33e5e90ea84',
                firstName: 'Skaut',
                lastName: '3',
                email: 'skaut3@skaut',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: '753f3124-00b5-4c54-a468-57c064a19467',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e76213f3-43bd-42ba-862a-5e497ef0addc',
                firstName: 'Skaut',
                lastName: '4',
                email: 'skaut4@skaut',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: 'd28f5e4b-a149-4d3f-8043-4b6bfea59435',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e76213f3-43bd-42ba-862a-5e497ef0addd',
                firstName: 'Director',
                lastName: 'Sports',
                email: 'director@director',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SPORTS_DIRECTOR',
                regionId: 'd28f5e4b-a149-4d3f-8043-4b6bfea59435',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e76213f3-43bd-42ba-862a-5e497ef0adde',
                firstName: 'Analysis',
                lastName: '',
                email: 'analysis@analysis',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ANALYTICS',
                regionId: 'd28f5e4b-a149-4d3f-8043-4b6bfea59435',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e76213f3-43bd-42ba-862a-5e497ef0addf',
                firstName: 'Region',
                lastName: 'Manager',
                email: 'region@region',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'REGION_MANAGER',
                regionId: 'd28f5e4b-a149-4d3f-8043-4b6bfea59435',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'b04bd194-ee2f-40d4-a7b9-673a88e61761',
                firstName: 'Komisja',
                lastName: 'Egzamin',
                email: 'komisja@skautoteka.info',
                phoneNumber: '123456789',
                password: await hashPassword('#Komisja2024'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '67939182-4af3-469c-a660-af8fadc70c22',
                firstName: 'Rafał',
                lastName: 'Stryczek',
                email: 'stryku2@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '3ca53b2c-59d6-4a14-a9e6-e2cb481d1681',
                firstName: 'Piotr',
                lastName: 'Jaguś',
                email: 'jaguspiotr@wp.pl',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'ADMIN',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '62333077-8d37-461d-9944-12cde0e7ed5c',
                firstName: 'Tomasz',
                lastName: 'Pęśko',
                email: 'tppesko@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '02201b9c-a23e-4b9a-84a3-d169b07dfb69',
                firstName: 'Aleksander',
                lastName: 'Gutkowski',
                email: 'gutkowskiAleksander@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'a971bb59-bebc-4473-b62c-15a2d7515440',
                firstName: 'Tomasz',
                lastName: 'Zacharski',
                email: 'anntomnik@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '9f0743d1-4adb-451e-80c9-eb7154437c89',
                firstName: 'Dawid',
                lastName: 'Drymel',
                email: 'dawiddrymel@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '90badfd1-7cb2-44db-bbbd-e8d946c328a3',
                firstName: 'Robert',
                lastName: 'Saganowski',
                email: 'rsaganowski98@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '4b7f55d2-1328-4ef6-9ea9-9c20952eb2c2',
                firstName: 'Jakub',
                lastName: 'Mazurskiewicz',
                email: 'jakubmazurkiewicz21@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e25972fd-07bc-4df3-ab25-27d0f2476d76',
                firstName: 'Patryk',
                lastName: 'Karczewski',
                email: 'jakubjanek1989@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'e7de9cd6-9c2c-41d1-91a6-4b93771470d0',
                firstName: 'Karol',
                lastName: 'Organiściak',
                email: 'organisciak.karol98@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '7d9a1598-12b1-4b38-aa0a-1eceff0eacf0',
                firstName: 'Paweł',
                lastName: 'Haller',
                email: 'pawel.haller@hotmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '3197e13c-7213-4549-9e1e-342987a027bf',
                firstName: 'Łukasz',
                lastName: 'Lubowiedzki',
                email: 'Lukasz.Lubowiedzki@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: 'df46768d-072a-496a-a9fa-48125cd57843',
                firstName: 'Łukasz',
                lastName: 'Papaj',
                email: 'piekarz98@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '493ccf4b-67c3-4c74-ac8c-467bc0ef3383',
                firstName: 'Vitali',
                lastName: 'Tsemokh',
                email: 'tsemokh.vitalii@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '321bcad7-c1c3-4caf-bf6b-5875bd801a19',
                firstName: 'Adam',
                lastName: 'Kujawski',
                email: 'kujawski.15@wp.pl',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: '8a446440-293e-4c2c-94de-fd20f78f47c6',
                firstName: 'Adam',
                lastName: 'Smuga',
                email: 'smugaadam0@gmail.com',
                phoneNumber: '123456789',
                password: await hashPassword('1234'),
                roleId: 'SCOUT',
                regionId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]

        await queryInterface.bulkInsert('Users', users, {})
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Users', null, {})

        try {
            await queryInterface.removeConstraint(
                'Users',
                'unique_email_constraint'
            )
        } catch (error) {
            console.log('No existing constraint found. Skipping removal.')
        }
    },
}
